apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rest-service
  labels:
    app.kubernetes.io/name: rest-service
    app.kubernetes.io/part-of: data-connect-hub
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rest-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: opendatahub
          podSelector:
            matchLabels:
              gateway.networking.k8s.io/gateway-name: odh-gateway
      ports:
        - port: 8443
          protocol: TCP
  egress:
    - {}
