controllerManager:
  image:
    repository: quay.io/opendatahub/odh-data-connect-hub-controller
    tag: odh-stable
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

relatedImages: {}

leaderElection: true

initDataConnectionTypes:
  enabled: true
