apiVersion: v1
kind: ConfigMap
metadata:
  name: opendatahub-dataconnecthub-config
  namespace: {{ .Release.Namespace }}
  labels:
    platform.opendatahub.io/managed: "true"
    {{- include "dc-controller.labels" . | nindent 4 }}
data:
  distribution.name: "Standalone"
  distribution.version: "0.0.0"
  controller.log.level: {{ .Values.platformConfig.logLevel | quote }}
  gateway.name: {{ .Values.platformConfig.gatewayName | quote }}
  gateway.namespace: {{ .Values.platformConfig.gatewayNamespace | quote }}
