apiVersion: v1
kind: ConfigMap
metadata:
  name: opendatahub-dataconnecthub-config
  namespace: {{ .Release.Namespace }}
  labels:
    platform.opendatahub.io/managed: "true"
    {{- include "dc-controller.labels" . | nindent 4 }}
data:
  distribution.name: {{ .Values.platformConfig.distributionName }}
  distribution.version: {{ .Values.platformConfig.distributionVersion | quote }}
  controller.log.level: {{ .Values.platformConfig.logLevel }}
  gateway.name: {{ .Values.platformConfig.gatewayName }}
  gateway.namespace: {{ .Values.platformConfig.gatewayNamespace }}
