{{- if .Values.initDataConnectionTypes.enabled }}
apiVersion: dataconnecthub.opendatahub.io/v1alpha1
kind: InitDataConnectionType
metadata:
  name: s3
  labels:
    {{- include "dc-controller.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  name: S3
  provider: s3
  description: "Amazon S3 compatible object storage"
  credentialsFields:
    - name: AWS_S3_ENDPOINT
      label: Endpoint
      description: "S3 endpoint URL (for non-AWS S3-compatible services)"
      required: false
      type: string
    - name: AWS_DEFAULT_REGION
      label: Region
      description: "AWS region"
      required: false
      type: string
      defaultValue: "us-east-1"
    - name: AWS_S3_BUCKET
      label: Bucket
      description: "S3 bucket name"
      required: true
      type: string
    - name: AWS_ACCESS_KEY_ID
      label: Access Key ID
      description: "AWS access key ID"
      required: true
      type: string
    - name: AWS_SECRET_ACCESS_KEY
      label: Secret Access Key
      description: "AWS secret access key"
      required: true
      type: string
---
apiVersion: dataconnecthub.opendatahub.io/v1alpha1
kind: InitDataConnectionType
metadata:
  name: postgres
  labels:
    {{- include "dc-controller.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  name: Postgres
  provider: postgres
  description: "Postgres data connection type"
  credentialsFields:
    - name: URI
      label: Uri
      description: "Postgres connection URI"
      required: true
      type: string
---
apiVersion: dataconnecthub.opendatahub.io/v1alpha1
kind: InitDataConnectionType
metadata:
  name: uri
  labels:
    {{- include "dc-controller.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  name: URI
  provider: uri
  description: "Generic URI data source"
  credentialsFields:
    - name: URI
      label: Uri
      description: "Data source URI"
      required: true
      type: string
    - name: TOKEN
      label: Token authentication
      description: "Authentication method for bearer token authentication"
      required: false
      type: string
    - name: BASIC
      label: Basic
      description: "The base64 encoded username:password for basic authentication"
      required: false
      type: string
---
apiVersion: dataconnecthub.opendatahub.io/v1alpha1
kind: InitDataConnectionType
metadata:
  name: huggingface
  labels:
    {{- include "dc-controller.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  name: HuggingFace
  provider: huggingface
  description: "Hugging Face model and dataset hub"
  credentialsFields:
    - name: HF_URI
      label: URI
      description: "HuggingFace URI"
      required: true
      type: string
    - name: HF_TOKEN
      label: Token
      description: "Huggingface token"
      required: false
      type: string
---
apiVersion: dataconnecthub.opendatahub.io/v1alpha1
kind: InitDataConnectionType
metadata:
  name: oci
  labels:
    {{- include "dc-controller.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  name: OCI
  provider: oci
  description: "OCI-compatible container registry"
  credentialsFields:
    - name: .dockerconfigjson
      label: Docker config json
      description: "Docker config json file"
      required: true
      type: string
    - name: OCI_HOST
      label: OCI host name
      description: "OCI registry host name"
      required: true
      type: string
{{- end }}
