resources:
- manager.yaml
- platform-config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/opendatahub/odh-data-connect-hub-controller
  digest: sha256:e44f8bf8b769deb29dbf63f960921eee9393789be2a9c468be333a26ca796f8c
