[package]
name = "db-sync"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
commons = { workspace = true }
pg-meta-store = { workspace = true }
config = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
